version: '3.8'
services:
  server:
    container_name: genieserves
    build:
      context: .
      dockerfile: ./server/server.dockerfile
    ports:
      - '5000:5000'
    env_file:
      - ./server/.env
  webapp:
    container_name: geniespeaks
    build:
      context: .
      dockerfile: ./webapp/webapp.dockerfile
    ports:
      - '80:80'
    stdin_open: true
    tty: true
    depends_on:
      - server