apiVersion: v1
kind: Service
metadata:
  name: webapp-cluster-ip-service
spec:
  type: NodePort
  selector:
    component: webapp
  ports:
    - port: 80
      targetPort: 80
      # Only Use in Development
      nodePort: 31515
