name: CI-CD

on:
  pull_request:
  push:

jobs:
  # dast:
  #   uses: ./.github/workflows/dast_baseline_zap.yaml

  scraper_shiftleft_ng_sast:
    uses: ./.github/workflows/scraper_shiftleft_ng_sast.yml

  server_shiftleft_ng_sast:
    uses: ./.github/workflows/server_shiftleft_ng_sast.yml

  webapp_shiftleft_ng_sast:
    uses: ./.github/workflows/webapp_shiftleft_ng_sast.yml

  development:
    name: Development Deployment
    needs:
    - scraper_shiftleft_ng_sast
    - server_shiftleft_ng_sast
    - webapp_shiftleft_ng_sast
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Testing
      run: |
        echo "Development Testing"

  production:
    name: Production Deployment
    needs:
    - scraper_shiftleft_ng_sast
    - server_shiftleft_ng_sast
    - webapp_shiftleft_ng_sast
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Testing
      run: |
        echo "Production Testing"
    
  check_annotations:
    name: Check Annotations
    needs:
    - development

    if: always() && github.event_name == 'pull_request'

    runs-on: ubuntu-latest

    steps:
    - name: Testing
      run: |
        echo "check_annotations Testing"
