name: CI CD Shiftleft PR Scans

on:
  pull_request:
    branches:
      - master
      - integration
  workflow_dispatch:

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      geniescrapes: ${{ steps.filter.outputs.geniescrapes }}
      server: ${{ steps.filter.outputs.server }}
      webapp: ${{ steps.filter.outputs.webapp }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            geniescrapes:
              - 'geniescrapes/**'
            server:
              - 'server/**'
            webapp:
              - 'webapp/**'

      - name: Check geniescrapes folder changes
        if: steps.filter.outputs.geniescrapes == 'true'
        run: echo "geniescrapes folder changes"

      - name: Check server folder changes
        if: steps.filter.outputs.server == 'true'
        run: echo "server folder changes"
      
      - name: Check webapp folder changes
        if: steps.filter.outputs.webapp == 'true'
        run: echo "webapp folder changes"


  scraper_shiftleft_ng_sast:
    name: Scraper Shiftleft NG SAST
    needs:
      - paths-filter
    uses: ./.github/workflows/scraper_shiftleft_ng_sast.yml
    if: needs.paths-filter.outputs.geniescrapes == 'true'
    secrets: 
      SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}


  server_shiftleft_ng_sast:
    name: Server Shiftleft NG SAST
    needs:
      - paths-filter
    if: needs.paths-filter.outputs.server == 'true'
    uses: ./.github/workflows/server_shiftleft_ng_sast.yml
    secrets: 
      SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}


  webapp_shiftleft_ng_sast:
    name: Webapp Shiftleft NG SAST
    needs:
      - paths-filter
    if: needs.paths-filter.outputs.webapp == 'true'
    uses: ./.github/workflows/webapp_shiftleft_ng_sast.yml
    secrets: 
      SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
