name: CI CD Deploy and DAST Merge Scans

on:
  push:
    branches:
      - master
      - dev
      - test
  workflow_dispatch:

jobs:
  paths-filter:
    name: Trigger Folder Tests
    runs-on: ubuntu-latest
    outputs:
      geniescrapes: ${{ steps.filter.outputs.geniescrapes }}
      server: ${{ steps.filter.outputs.server }}
      webapp: ${{ steps.filter.outputs.webapp }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            geniescrapes:
              - 'geniescrapes/**'
            server:
              - 'server/**'
            webapp:
              - 'webapp/**'

      - name: Check geniescrapes folder changes
        if: steps.filter.outputs.geniescrapes == 'true'
        run: echo "geniescrapes folder changes"

      - name: Check server folder changes
        if: steps.filter.outputs.server == 'true'
        run: echo "server folder changes"
      
      - name: Check webapp folder changes
        if: steps.filter.outputs.webapp == 'true'
        run: echo "webapp folder changes"


  scraper_dev_deploy:
    name: Scraper Dev Container Deploy
    if: needs.paths-filter.outputs.geniescrapes == 'true'
    needs:
    - paths-filter
    uses: ./.github/workflows/scraper_deploy.yml
    with:
      app_name: geniescraper
      registry: geniespeaks.azurecr.io/
      registry_uri: https://geniespeaks.azurecr.io/
      environment: ${{ secrets.environment }}
    secrets:
      azure_username: ${{ secrets.AzureAppService_ContainerUsername_d24aa6b3a1bb4b34be0b64a433b28dd6 }}
      azure_password: ${{ secrets.AzureAppService_ContainerPassword_4abe61323a504b1a9bb359aec8377a49 }}
      azure_publish_profile: ${{ secrets.AzureAppService_PublishProfile_0fc8a61af9b04ee7938c4a15288510bf }}


  server_dev_deploy:
    name: Server Dev Container Deploy
    # environment: development
    needs:
      - paths-filter
    if: needs.paths-filter.outputs.server == 'true'
    uses: ./.github/workflows/server_deploy.yml
    with:
      app_name: genieserves
      registry: docker.io
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password_token: ${{ secrets.DOCKERHUB_PASSWORD }}
      azure_publish_profile: ${{ secrets.AZURE_GENIESERVES_PUBLISHPROFILE }}

  server_dast_zap_api:
    name: DAST ZAP API Scan
    needs:
      - server_dev_deploy
    uses: ./.github/workflows/dast_zap_api.yml


  webapp_dev_deploy:
    name: Webapp Dev Container Deploy
    needs:
      - paths-filter
    if: needs.paths-filter.outputs.webapp == 'true'
    # environment: development
    uses: ./.github/workflows/webapp_deploy.yml
    with:
      app_name: geniespeaks
      registry: docker.io
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password_token: ${{ secrets.DOCKERHUB_PASSWORD }}
      azure_publish_profile: ${{ secrets.AZURE_GENIESPEAKS_PUBLISHPROFILE }}

  webapp_dev_static_app_deploy:
    name: Webapp Dev Static App Deploy
    needs:
      - paths-filter
    if: needs.paths-filter.outputs.webapp == 'true'
    # environment: development
    uses: ./.github/workflows/azure-static-web-apps-mango-bush-0d243c810.yml
    secrets:
      mango_bush_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_BUSH_0D243C810 }}

  webapp_dast_zap_baseline:
    name: DAST ZAP Baseline Scan
    needs:
      - webapp_dev_deploy
      - webapp_dev_static_app_deploy
    uses: ./.github/workflows/dast_zap_baseline.yml
