# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: DAST API Scan

on:
  # pull_request:
  #   branches:
  #     - master
  workflow_call:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ZAP API Scan
        uses: zaproxy/action-api-scan@v0.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          format: openapi
          target: 'https://gsserver.azurewebsites.net/apis'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
